-- DAS Assignment

-- CREATE DATABASE
CREATE DATABASE E_Bookstore;
GO

USE E_Bookstore;
GO

-- CREATE TABLES
CREATE TABLE Publisher (
	PublisherID CHAR(5) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	PhoneNumber CHAR(12) NOT NULL );
GO

CREATE TABLE Member (
	MemberID CHAR(5) Primary Key,
	FirstName VARCHAR(25) NOT NULL,
	LastName VARCHAR(25) NOT NULL,
	Gender CHAR(1) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	PhoneNumber CHAR(12) NOT NULL );
Go

CREATE TABLE Orders (
	OrderID CHAR(5) PRIMARY KEY,
	OrderDate DATE NOT NULL,
	DeliveryStatus VARCHAR(10) NOT NULL,
	PublisherID CHAR(5) NOT NULL REFERENCES Publisher(PublisherID) );
GO

CREATE TABLE Book (
	ISBN CHAR(20) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	Price DECIMAL(4,2) NOT NULL,
	Synopsis VARCHAR(255),
	PublishDate DATE NOT NULL,
	StockQuantity INTEGER NOT NULL,
	Genre VARCHAR(15),
	Author VARCHAR(50) NOT NULL,
	PublisherID CHAR(5) NOT NULL REFERENCES Publisher(PublisherID) );
GO

CREATE TABLE Book_Orders (
	ISBN CHAR(20) NOT NULL REFERENCES BOOK(ISBN),
	OrderID CHAR(5) NOT NULL REFERENCES Orders(OrderID),
	OrderQuantity INTEGER NOT NULL,
	PRIMARY KEY (ISBN, OrderID) );
GO

CREATE TABLE Sale (
	SaleID CHAR(5) PRIMARY KEY,
	SaleDate DATE NOT NULL,
	DeliveryStatus VARCHAR(10) NOT NULL,
	MemberID CHAR(5) NOT NULL REFERENCES Member(MemberID) );		
GO

CREATE TABLE Book_Sale (
	ISBN CHAR(20) NOT NULL REFERENCES Book(ISBN),
	SaleID CHAR(5) NOT NULL REFERENCES Sale(SaleID),
	SaleQuantity INTEGER NOT NULL,
	PRIMARY KEY (ISBN, SaleID) );
GO

CREATE TABLE Cart_Item (
	CartID CHAR(5) PRIMARY KEY,
	Quantity INTEGER NOT NULL, 
	MemberID CHAR(5) NOT NULL REFERENCES Member(MemberID),
	ISBN CHAR(20) NOT NULL REFERENCES Book(ISBN) );
GO

CREATE TABLE Feedback (
	FeedbackID CHAR(5) PRIMARY KEY,
	Comment VARCHAR(150),
	Rating INTEGER NOT NULL,
	MemberID CHAR(5) NOT NULL REFERENCES Member(MemberID),
	ISBN CHAR(20) NOT NULL REFERENCES Book(ISBN) );
GO


